import { Typography } from '@mui/material';

import { AuthAccessLevel } from '@/constants';
import { withPageSettings } from '@/utils';

const Home = () => {
  return (
    <>
      <Typography variant="h2" textAlign="center" marginTop={4}>
        Welcome to Shaper GAP®
      </Typography>
    </>
  );
};

export const getServerSideProps = withPageSettings({
  auth: { accessLevel: AuthAccessLevel.Public },
  metaData: {
    meta: [
      {
        name: 'description',
        content: 'Generated by create next app',
      },
    ],
  },
});

export default Home;
