import { AuthAccessLevel } from '@/constants';
import { Dashboard } from '@/page-content';
import { withPageSettings } from '@/utils';

const Home = () => {
  return <Dashboard />;
};

export const getServerSideProps = withPageSettings({
  auth: { accessLevel: AuthAccessLevel.Public },
  metaData: {
    meta: [
      {
        name: 'description',
        content: 'Generated by create next app',
      },
    ],
  },
});

export default Home;
